routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SeoController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\MobileAppController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\DevelopmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { return view('home'); });

Route::get('/portfolio', [PortfolioController::class, 'index']);

Route::get('/terms-and-conditions', function () { return view('terms'); });
Route::get('/acceptable-use-policy', function () { return view('acceptable-use'); });

Route::prefix('services')->group(function () {
    Route::get('/website-design', [DesignController::class, 'index']);
    Route::get('/website-development', [DevelopmentController::class, 'index']);
    Route::get('/mobile-app-development', [MobileAppController::class, 'index']);
    Route::get('/ecommerce-online-store-development', [StoreController::class, 'index']);
    Route::get('/graphic-design', function () { return view('services.graphic'); });
    Route::get('/search-engine-optimisation', [SeoController::class, 'index']);
    Route::get('/website-hosting', function () { return view('services.hosting'); });
    // Route::get('/drone-aerial-photography', function () { return view('services.drone'); });
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    use HasFactory;

    /**
     * Get the features in an unencoded format.
     *
     * @param  string  $value
     * @return void
     */
    public function getFeaturesAttribute($value)
    {
        return json_decode(json_decode($value, true), true);
    }

    /**
     * Set the slug for the projects client name.
     *
     * @param  string  $value
     * @return void
     */
    public function getClientSlugAttribute($value)
    {
        return Str::slug($this->client);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DesignController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class DesignController extends Controller
{
    public function index()
    {
        $projects = Project::whereId(11)->get();
        
        return view('services.design', compact('projects'));
    }
}

app/Http/Controllers/DevelopmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class DevelopmentController extends Controller
{
    public function index()
    {
        $projects = Project::whereId(9)->get();
        
        return view('services.development', compact('projects'));
    }
}

app/Http/Controllers/MobileAppController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class MobileAppController extends Controller
{
    public function index()
    {
        $projects = Project::whereId(8)->get();
        
        return view('services.mobile', compact('projects'));
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class PortfolioController extends Controller
{
    public function index()
    {
        $projects = Project::orderBy('date', 'desc')->paginate(12);

        return view('portfolio', compact('projects'));
    }
}

app/Http/Controllers/SeoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class SeoController extends Controller
{
    public function index()
    {
        $projects = Project::whereId(8)->get();
        
        return view('services.seo', compact('projects'));
    }
}

app/Http/Controllers/StoreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class StoreController extends Controller
{
    public function index()
    {
        $projects = Project::whereId(6)->get();
        
        return view('services.store', compact('projects'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/acceptable-use.blade.php
@extends('layouts.master')

@section('meta-title', 'Acceptable Use Policy | FireBulb Media')
@section('meta-description', 'Please review our hosting services acceptable use policy.')
@section('bg-img', '')

@section('content')
    <x-page-header>
        <x-slot name="title">
            Acceptable Use Policy
        </x-slot>

        This policy outlines our acceptable use guidelines for our hosting services. We reserve the right to update this page without notice.
    </x-page-header>

    <section class="container mx-auto prose mt-56 mb-32">
        <p>This Acceptable Use Policy describes prohibited uses of the services offered by <a href="{{ url('/') }}">{{ url('/') }}</a>. (the “Services”) and the website located at <a href="{{ url('/') }}">{{ url('/') }}</a> (the “Firebulb Media website”). The examples described in this Policy are not exhaustive. We may modify this Policy at any time by posting a revised version on the Firebulb Media website.</p>
        <p>By using the Services or accessing the Firebulb Media website, you agree to the latest version of this policy. If you violate the Policy or authorise or help others to do so, we may suspend or terminate your use of our website hosting services.</p>

        <h3>Illegal or Offensive Content</h3>
        <p>You may not use, or encourage, promote, facilitate or instruct others to use, the Services or Firebulb Media website for any illegal, harmful, fraudulent, infringing or offensive use, or to transmit, store, display, distribute or otherwise make available content that is illegal, harmful, fraudulent, infringing or offensive. Prohibited activities or content include, but are not limited to:</p>

        <ul>
            <li><b>Illegal, Harmful or Fraudulent Activities</b> - Any activities that are illegal, that violate the rights of others, or that may be harmful to others, our operations or reputation, including disseminating, promoting or facilitating child pornography, offering or disseminating fraudulent goods, services, schemes, or promotions, make-money-fast schemes, or ponzi and pyramid schemes.</li>
            <li><b>Infringing Content</b> - Content that infringes or misappropriates the intellectual property or proprietary rights of others.</li>
            <li><b>Offensive Content</b> - Content that is defamatory, obscene, abusive, invasive of privacy, or otherwise objectionable, including content that is pornographic in nature or discriminatory against any race, religion, or creed.</li>
            <li><b>Harmful Content</b> - Content or other computer technology that may damage, interfere with, surreptitiously intercept, or expropriate any system, program, or data, including viruses, Trojan horses or worms.</li>
        </ul>

        <h3>Network Abuse</h3>

        <p>You may not make network connections to any users, hosts, or networks unless you have permission to communicate with them. Prohibited activities include, but are not limited to:</p>

        <ul>
            <li><b>User Solicitation</b> - Soliciting login credentials from another user or using or attempting to use another user’s account, username, or password without their permission. Monitoring or Crawling. Monitoring or crawling of a System that impairs or disrupts the System being monitored or crawled.</li>
            <li><b>Intentional Interference</b> - Interfering with the proper functioning of the Services, including any deliberate attempt to overload a network or System.</li>
            <li><b>Avoiding System Restrictions</b> - Using manual or electronic means to avoid any use limitations placed on a System, such as access, message, seat, API, bot, or contact restrictions.</li>
        </ul>

        <h3>Security Violations</h3>

        <p>You may not violate the security or integrity of any network, computer or communications system, software application, or network or computing device (each, a “System”). Prohibited activities include, but are not limited to:</p>

        <ul>
            <li><b>Unauthorised Access</b> - Accessing or using any System without permission, including attempting to probe, scan, or test the vulnerability of a System or to breach any security or authentication measures used by a System.</li>
            <li><b>Interception</b> - Monitoring of data or traffic on a System without permission.</li>
            <li><b>Third Party Services</b> - Developing any applications that interact with the Services or other users’ content or information without our written consent.</li>
        </ul>

        <h3>Monitoring and Enforcement</h3>

        <p>We reserve the right, but do not assume the obligation, to investigate any violation of this Policy or misuse of the Services or Firebulb Media Website. We may:</p>

        <ul>
            <li>Investigate violations of this policy or misuse of our hosting services</li>
            <li>Remove or disable any content or resource that violates this policy or any other agreement we have with you for use of our hosting services.</li>
        </ul>

        <h3>Reporting Violations</h3>

        <p>If you become aware of any violation of this Policy, please <a href="mailto:{{ config('business.email') }}">contact us</a> immediately and provide us with assistance, as requested, to stop or remedy the violation.</p>

    </section>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/portfolio.blade.php
@extends('layouts.master')

@section('meta-title', 'Design Portfolio | FireBulb Media')
@section('meta-description', 'We have been designing website and applications for the last 10 years. View our profile to see some of our work.')
@section('bg-img', 'hexagons')

@section('content')
    <x-page-header>
        <x-slot name="title">
            Our Portfolio
        </x-slot>

        We take pride in all the work we complete, and get just as passionate about your business as you do. View some of our recently completed projects below for ideas on what we can do for your business.
    </x-page-header>

    <section class="container mx-auto my-32 p-4 xl:my-48">
        @foreach($projects as $index => $project)
        <div class="px-0 3xl:px-48 4xl:px-72 @if(!$loop->first) mt-10 @endif">
            
            <div class="relative block lg:flex">

                @if($loop->first)
                    <img class="hidden xl:block absolute -top-48 left-[-129px] z-10" src="/img/ed_leaning.png" srcset="/img/ed_leaning@2x.png 2x" alt="Ed Leaning" />
                @endif

                @if($index == 9)
                    <img class="hidden xl:block absolute bottom-0 left-[-145px] z-10" src="/img/ed_side.png" srcset="/img/ed_side@2x.png 2x" alt="Ed Pointing Side" />
                @endif
                
                <div>
                    <Carousel project="{{ $project->client_slug }}" :slide-count="{{ $project->slides }}"></Carousel>
                </div>
                <div class="mt-6 lg:ml-10 lg:mt-0">
                    @if(isset($project->url))
                        <a class="text-gray-800 hover:text-green-700 duration-300" href="{{ $project->url }}" target="_blank" rel="nofollow"><h3 class="text-3xl font-varela">{{ $project->client }}</h3></a>
                    @else
                        <h3 class="text-3xl text-gray-800 font-varela">{{ $project->client }}</h3>
                    @endif
                    <div class="text-green-400 font-bold mt-2">{{ $project->date }}</div>
                    <div class="mt-4 text-gray-600">
                        {!! $project->description !!}
                    </div>

                    <ul class="font-bold mt-4 text-sm">
                        @foreach($project->features as $feature)
                        <li class="flex items-center @if(!$loop->first) mt-2 @endif">
                            <img class="w-6 h-6" src="/img/svg/{{ $feature['icon'] }}" alt="Feature Icon" />
                            <span class="ml-2">{{ $feature['description'] }}</span>
                        </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        @endforeach
        
    </section>
@endsection

resources/views/services/design.blade.php
@extends('layouts.master')

@section('meta-title', 'Website Design Services Albury Wodonga | FireBulb Media')
@section('meta-description', 'FireBulb Media provide professional website design services in Albury Wodonga and surrounding areas. We are your all-in-one solution for your website')
@section('bg-img', 'hexagons')

@section('content')
    <x-page-header>
        <x-slot name="title">
            Website Designers in Albury Wodonga
        </x-slot>

        We are professional website designers situated in Albury Wodonga. We pride ourselves on our modern designs purpose built specifically for the needs of our clients.
    </x-page-header>

    <section class="relative container mx-auto mt-48">
        <div class="relative -mx-120 md:-mx-72 xl:mx-10">
            <object data="/img/backgrounds/green-blob.svg" type="image/svg+xml" aria-label="Header Blob"></object>
        </div>
        <div class="absolute -top-36 inset-0 md:flex md:items-center md:justify-center md:top-10 lg:px-10 xl:px-48">
            <div class="relative w-2/3 mx-auto md:w-1/2 md:flex-shrink-0 xl:w-2/5 2xl:w-1/2">
                <img src="/img/ed_attention.png" srcset="/img/ed_attention@2x.png 2x" alt="Ed Megaphone" />
            </div>
            <div class="px-4 lg:px-0 lg:pr-10">
                <h2 class="text-lg sm:text-2xl text-green-900 lg:text-2xl 2xl:text-4xl font-varela">Get Attention Online With A Website Designed Specifically For Your Needs</h2>
                <div class="mt-4 text-sm lg:text-base text-green-800">
                    <p>Give your brand the love it deserves with a beautifully designed, professional website that'll be sure to grab the attention of your customers.</p>

                    <p class="mt-3">FireBulb understands that you only have a few seconds to leave a positive impression before customers return to the search results. We can assist you in providing a good user experience that will make potential customers pick you every time. We provide high quality website designs that perfectly complement your branding, giving you a professional online platform that people can trust.</p>

                    <p class="mt-3">Give your business the competitive edge with a professionally designed website from FireBulb.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="container mx-auto mt-32 p-4">
        <h2 class="text-center text-gray-800 text-2xl md:text-3xl lg:text-4xl relative lg:max-w-md mx-auto font-varela">
            Take A Look At Our 
            <span class="inline-block relative">
                Design Process
                <div class="absolute bottom-1 left-0 bg-green-200 rounded h-4 w-full -z-1"></div>
            </span>
             In Action
        </h2>
        <p class="mt-2 text-center text-green-700 text-lg font-bold">Let us show you how easy the process is!</p>

        <div class="mt-10 md:grid md:grid-cols-2 md:gap-2 2xl:grid-cols-4 2xl:gap-4">
            <div class="">
                <div class="relative text-center max-w-md mx-auto">
                    <img class="absolute w-36 h-36 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" src="/img/backgrounds/step-1.svg" alt="Step 1" />
                    <div class="absolute w-full h-full flex flex-col justify-center items-center p-16">
                        <h3 class="text-xl font-varela text-gray-800 md:text-3xl">Discussion</h3>
                        <img class="w-14 mt-2" src="/img/underline.svg" alt="Heading Underline" />
                        <p class="text-sm mt-2 text-gray-600 md:text-base">This initial phase is where we discuss your needs, as well as get an understanding of your business and your vision for the project. You’ll have an opportunity to ask us any of your burning questions as well.</p>
                    </div>
                    <img src="/img/backgrounds/blob-1.svg" alt="Blob 1"/>
                </div>
            </div>

            <div class="mt-10 md:mt-48 xl:mt-64">
                <div class="relative text-center max-w-md mx-auto">
                    <img class="absolute w-36 h-36 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" src="/img/backgrounds/step-2.svg" alt="Step 2" />
                    <div class="absolute w-full h-full flex flex-col justify-center items-center p-16">
                        <h3 class="text-xl font-varela text-gray-800 md:text-3xl">Proposal</h3>
                        <img class="w-14 mt-2" src="/img/underline.svg" alt="Heading Underline" />
                        <p class="text-sm mt-2 text-gray-600 md:text-base">Once we’ve covered everything we need to know about the project, we’ll write up your proposal document which outlines the requirements of the project and an itemised list of the costs involved in bringing your site to fruition.</p>
                    </div>
                    <img src="/img/backgrounds/blob-2.svg" alt="Blob 2"/>
                </div>
            </div>

            <div class="mt-10">
                <div class="relative text-center max-w-md mx-auto">
                    <img class="absolute w-36 h-36 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" src="/img/backgrounds/step-3.svg" alt="Step 3" />
                    <div class="absolute w-full h-full flex flex-col justify-center items-center p-16">
                        <h3 class="text-xl font-varela text-gray-800 md:text-3xl">Design</h3>
                        <img class="w-14 mt-2" src="/img/underline.svg" alt="Heading Underline" />
                        <p class="text-sm mt-2 text-gray-600 md:text-base">Once you’re happy with the proposal, we’ll collect any required images and content from you to get started. You'll receive updates and previews throughout the development of your website.</p>
                    </div>
                    <img src="/img/backgrounds/blob-3.svg" alt="Blob 3"/>
                </div>
            </div>

            <div class="mt-10 md:mt-48 xl:mt-64">
                <div class="relative text-center max-w-md mx-auto">
                    <img class="absolute w-36 h-36 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" src="/img/backgrounds/step-4.svg" alt="Step 4" />
                    <div class="absolute w-full h-full flex flex-col justify-center items-center p-16">
                        <h3 class="text-xl font-varela text-gray-800 md:text-3xl">Feedback</h3>
                        <img class="w-14 mt-2" src="/img/underline.svg" alt="Heading Underline" />
                        <p class="text-sm mt-2 text-gray-600 md:text-base">Once the site is nearing completion, we’ll give you access to the final version where you can test features and ensure you’re happy with the outcome. Once you’re happy we’ll release the project into the wild for your audience to enjoy.</p>
                    </div>
                    <img src="/img/backgrounds/blob-4.svg" alt="Blob 4"/>
                </div>
            </div>
        </div>
    </section>

    <section class="mt-20 p-4 grid grid-cols-1 gap-20 grid-rows-2 md:grid-cols-2 md:gap-y-20 md:gap-5 md:p-4 lg:container lg:mx-auto lg:grid-cols-3 2xl:gap-10 2xl:gap-y-20 2xl:px-48">
        <x-tile>
            <x-slot name="title">
                Utilising The Latest Tech
            </x-slot>
            <x-slot name="icon">
                tech
            </x-slot>

            We use only the latest bleeding edge technology and techniques to give our customers the best product possible, with industry leading features.
        </x-tile>

        <x-tile>
            <x-slot name="title">
                Designed To Get Attention
            </x-slot>
            <x-slot name="icon">
                attention
            </x-slot>

            Our designs focus on getting the attention of your audience. We thoroughly plan content placement to make your site easy to use and appealing.
        </x-tile>

        <x-tile>
            <x-slot name="title">
                Analytics Included
            </x-slot>
            <x-slot name="icon">
                binoculars
            </x-slot>

            We set up Google Analytics with all our websites, so you can track user engagement and website usage, allowing for easier optimisation of content.
        </x-tile>

        <x-tile>
            <x-slot name="title">
                Optimised For Fast Loading
            </x-slot>
            <x-slot name="icon">
                fast
            </x-slot>

            Website speed is important, which is why we use the latest industry techniques to ensure your website is blazing fast for your audience.
        </x-tile>

        <x-tile>
            <x-slot name="title">
                Common Browser Support
            </x-slot>
            <x-slot name="icon">
                browsers
            </x-slot>

            We test our websites on all modern browsers, including Chrome, Firefox, Edge and Safari to ensure a consistent experience for all your users.
        </x-tile>

        <x-tile>
            <x-slot name="title">
                Responsive Designs
            </x-slot>
            <x-slot name="icon">
                responsive
            </x-slot>

            We ensure our websites are built perfectly for any device, regardless of its size. So your users can have a functional experience on any device.
        </x-tile>
    </section>

    <section class="container mx-auto py-4 px-4 xl:px-20 2xl:px-0 mt-24 mb-36">
        <h2 class="font-varela text-center text-gray-800 text-2xl md:text-3xl lg:text-4xl relative lg:max-w-md mx-auto">
            Here's One Of Our  
            <span class="inline-block relative">
                Recent
                <div class="absolute bottom-1 left-0 bg-green-200 rounded h-4 w-full -z-1"></div>
            </span>
             Website Design Projects
        </h2>
        <p class="mt-2 text-center text-green-700 text-lg font-bold">See the quality of our work for yourself!</p>

        <div class="mt-10">
            @foreach($projects as $index => $project)
            <div class="px-0 3xl:px-48 4xl:px-72">
                
                <div class="relative block lg:flex">
                    <img class="hidden xl:block absolute bottom-0 left-[-145px] z-10" src="/img/ed_side.png" srcset="/img/ed_side@2x.png 2x" alt="Ed Pointing Side" />
                    
                    <div>
                        <Carousel project="{{ $project->client_slug }}" :slide-count="{{ $project->slides }}"></Carousel>
                    </div>
                    <div class="mt-6 lg:ml-10 lg:mt-0">
                        <h3 class="text-3xl text-gray-800 font-varela">{{ $project->client }}</h3>
                        <div class="text-green-400 font-bold mt-2">{{ $project->date }}</div>
                        <div class="mt-4 text-gray-600">
                            {!! $project->description !!}
                        </div>

                        <ul class="font-bold mt-4 text-sm">
                            @foreach($project->features as $feature)
                            <li class="flex items-center @if(!$loop->first) mt-2 @endif">
                                <img class="w-6 h-6" src="/img/svg/{{ $feature['icon'] }}" alt="Feature Icon" />
                                <span class="ml-2">{{ $feature['description'] }}</span>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
            @endforeach
        </div>

        <p class="mt-20 text-center text-lg text-gray-500">
            Want to see some more of our work? <a href="/portfolio" class="text-green-600 hover:underline font-bold">Check out our portfolio</a>
        </p>
    </section>
@endsection